# Site wide configuration

title:            Rcarrata's Blog
locale:           en_US
url:              https://rcarrata.com


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Roberto Carratala
  avatar: bio-photo.jpg
  bio: "Linux Geek. Devops & Automation enthusiast.           Working for Red Hat."
  email: #username
  disqus-shortname: rcarrata
  twitter: rcarrata_
  facebook: #username
  google:
    plus: 
    analytics: 
    verify:
    ad-client:
    ad-slot:
  github: rcarrata
  stackoverflow: 
  linkedin: rcarrata
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

google_analytics: UA-166866564-1

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]
